### ISSUE TITLE
Stats Resseting to 0 when you change Sheet Type.

### ISSUE THREAD

**Issue by SinnerZer0** [Skyl3lazer/foundry-5e-monster-maker-v10#74]
The concept of Giffyglyph Monster Maker was, and ever will be fantastic. 
I was sad when i saw the main one abandoned and pretty hyped seeing it continued here! 

But, personally, the layout of the sheet isn't the best for me, specially when mixing with other monsters from other books.
I noticed that whenever i try and change the Sheet type, from the Giffyglyph Module , to the base DnD 3.3.1 NPC sheet it breaks.

It convert some actions and characteristics, but, HP, AC , all the ability scores are zeroed or at 10.

Focus also that i'm still using 2014 rules, as are DnD 3.3.1.

So, there's any way to add the option to convert the Sheet into the base Foundry DnD sheets?

**Comment by Skyl3lazer** [comment]
The stats in the GMMC sheet are largely stored in the same places as the default sheets, but there are several instances where that isn't the case. For some values, they're stored in the module's metadata so they can change on the fly. These are mainly where the scaler determines the value, rather than any default calculation:

- Armor class
- Proficiency
- Hit points/dice

Additionally, the ability scores both scale and are ranked from top to bottom.

Unfortunately it's not really viable to convert these into 5e values. 

Take a monster, for example, wearing studded leather with a dex of 10. It's a Grunt Striker, CL10. According to D&D it should still have 12 AC. But because it's scalar nature, it will have an AC of 16.  To represent that in 5e terms, I'd have to make a bunch of modifications to how I store the AC to make it flat (natural) armor, etc. Those values would then have to be constantly updated.

These changes would only matter if you tried to convert scalar monsters back into non-scalar ones. While it's technically possible, the juice isn't worth the squeeze. If you want a scalar monster, make it scalar. If you don't, then don't.

--
As for abilities, each ability has its own sheet that can be changed. Scalar abilities have nothing in common whatsoever with 5e ones, it's entirely metadata that goes through a completely separate workflow within the mod for everything from how it rolls to how it displays. A scalar ability will never work on a non-scalar monster in any scenario.

**Comment by Skyl3lazer** [comment]
Worth noting that you can convert monsters to scalar from 5e initially by changing the sheet, so it should be very easy to turn monsters of any type that follow default 5e sheet data into a scalar creature.
